# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee', models.CharField(max_length=256)),
                ('attending_max', models.IntegerField(default=0)),
                ('attending_num', models.IntegerField(default=0)),
                ('guest_names', models.CharField(max_length=1024)),
                ('entree1', models.CharField(max_length=128)),
                ('entree2', models.CharField(max_length=128)),
                ('hotel', models.BooleanField(default=False)),
                ('shuttle_to_time', models.IntegerField(default=0)),
                ('shuttle_from_time', models.IntegerField(default=0)),
                ('attending', models.BooleanField(default=False)),
                ('responded', models.BooleanField(default=False)),
            ],
        ),
    ]
