# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='side',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='guest',
            name='entree1',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='guest',
            name='entree2',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='guest',
            name='guest_names',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
