# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_auto_20161213_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShuttleFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=32)),
                ('seats_max', models.IntegerField(default=0)),
                ('seats_free', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ShuttleTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=32)),
                ('seats_max', models.IntegerField(default=0)),
                ('seats_free', models.IntegerField(default=0)),
            ],
        ),
    ]
