# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0003_shuttlefrom_shuttleto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='attending_max',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='guest',
            name='attending_num',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='guest',
            name='entree1',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='guest',
            name='entree2',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='guest',
            name='guest_names',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='guest',
            name='shuttle_from_time',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='guest',
            name='shuttle_to_time',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='guest',
            name='side',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
